import { ProductType } from "./productTypes";

const products:ProductType[] = [ 
  {
    id: 1,
    name: "Adidas CoreFit T-Shirt",
    shortDescription: "A comfortable and lightweight classic.",
    description: "Experience the perfect blend of comfort and performance with the CoreFit T-Shirt. Made with breathable, moisture-wicking fabric. Ideal for workouts or everyday casual wear.",
    price: 39.99,
    sizes: ["s", "m", "l", "xl", "xxl"],
    colors: ["gray", "purple", "green"],
    images: {
      gray: "https://picsum.photos/id/10/400/300", 
      purple: "https://picsum.photos/id/10/400/300", // Same ID: same image
      green: "https://picsum.photos/id/10/400/300",  // Same ID: same image
    },
  },
  {
    id: 2,
    name: "Nike Dri-FIT Running Shorts",
    shortDescription: "Stay dry and focused on your run.",
    description: "Lightweight running shorts featuring Nike Dri-FIT technology to move sweat away from your skin. Includes an internal key pocket and an elastic waistband with drawcord.",
    price: 49.95,
    sizes: ["xs", "s", "m", "l", "xl"],
    colors: ["black", "red", "blue"],
    images: {
      black: "https://picsum.photos/id/13/400/300",
      red: "https://picsum.photos/id/13/400/300",
      blue: "https://picsum.photos/id/13/400/300",
    },
  },
  {
    id: 3,
    name: "Puma Training Hoodie",
    shortDescription: "Warm and cozy for your post-workout cool down.",
    description: "A soft fleece training hoodie with an adjustable drawstring hood and a kangaroo pocket. Perfect for layering during colder months or for lounging.",
    price: 65.00,
    sizes: ["m", "l", "xl", "xxl"],
    colors: ["navy", "charcoal", "olive"],
    images: {
      navy: "https://picsum.photos/id/16/400/300",
      charcoal: "https://picsum.photos/id/16/400/300",
      olive: "https://picsum.photos/id/16/400/300",
    },
  },
  {
    id: 4,
    name: "Under Armour Compression Leggings",
    shortDescription: "Support and recovery for peak performance.",
    description: "These leggings offer serious compression to aid muscle recovery. Four-way stretch construction moves better in every direction. Great for high-intensity training.",
    price: 79.50,
    sizes: ["s", "m", "l"],
    colors: ["black", "white"],
    images: {
      black: "https://picsum.photos/id/19/400/300",
      white: "https://picsum.photos/id/19/400/300",
    },
  },
  {
    id: 5,
    name: "Reebok Classic Leather Sneakers",
    shortDescription: "Timeless style and everyday comfort.",
    description: "The iconic Reebok Classic Leather shoe with a soft garment leather upper and a lightweight cushioned midsole. A perfect retro-inspired look for your everyday casual style.",
    price: 85.00,
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["white", "black", "gum"],
    images: {
      white: "https://picsum.photos/id/21/400/300",
      black: "https://picsum.photos/id/21/400/300",
      gum: "https://picsum.photos/id/21/400/300",
    },
  },
  {
    id: 6,
    name: "New Balance 990v5",
    shortDescription: "Premium running shoe built for stability.",
    description: "A heritage running shoe known for its superior comfort, durability, and support. Features a pigskin/mesh upper and ENCAP midsole technology.",
    price: 175.00,
    sizes: ["8", "8.5", "9", "9.5", "10", "11"],
    colors: ["grey", "black", "navy"],
    images: {
      grey: "https://picsum.photos/id/24/400/300",
      black: "https://picsum.photos/id/24/400/300",
      navy: "https://picsum.photos/id/24/400/300",
    },
  },
  {
    id: 7,
    name: "The North Face Resolve Jacket",
    shortDescription: "Waterproof and breathable protection.",
    description: "A lightweight, packable jacket for rain protection on the trail. Features DryVent™ technology, a fully adjustable hood, and elastic cuffs.",
    price: 99.00,
    sizes: ["s", "m", "l", "xl"],
    colors: ["yellow", "red", "black"],
    images: {
      yellow: "https://picsum.photos/id/27/400/300",
      red: "https://picsum.photos/id/27/400/300",
      black: "https://picsum.photos/id/27/400/300",
    },
  },
  {
    id: 8,
    name: "Columbia Convertible Pants",
    shortDescription: "Two-in-one outdoor versatility.",
    description: "These pants easily convert to shorts via zippered legs. Made with Omni-Shade™ UPF 50 sun protection fabric. Perfect for hiking and variable weather.",
    price: 60.00,
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["fossil", "sage"],
    images: {
      fossil: "https://picsum.photos/id/30/400/300",
      sage: "https://picsum.photos/id/30/400/300",
    },
  },
  {
    id: 9,
    name: "Patagonia Better Sweater Fleece Vest",
    shortDescription: "Warm, low-bulk vest for layering.",
    description: "A warm, midweight polyester fleece vest made of 100% recycled material. Features a full-zip front and two zippered handwarmer pockets. Fair Trade Certified™ sewn.",
    price: 89.00,
    sizes: ["s", "m", "l", "xl"],
    colors: ["oatmeal", "nickel", "deep-sea"],
    images: {
      oatmeal: "https://picsum.photos/id/32/400/300",
      nickel: "https://picsum.photos/id/32/400/300",
      "deep-sea": "https://picsum.photos/id/32/400/300",
    },
  },
  {
    id: 10,
    name: "Marmot PreCip Eco Jacket",
    shortDescription: "Earth-friendly, waterproof rain gear.",
    description: "Made with a PFC-free DWR and 100% recycled nylon face fabric. This jacket is lightweight, packable, and features Marmot's environmentally conscious NanoPro™ fabric.",
    price: 120.00,
    sizes: ["xs", "s", "m", "l"],
    colors: ["arctic", "lava"],
    images: {
      arctic: "https://picsum.photos/id/35/400/300",
      lava: "https://picsum.photos/id/35/400/300",
    },
  },
  {
    id: 11,
    name: "Adidas Essential Crewneck Sweatshirt",
    shortDescription: "Everyday comfort with subtle branding.",
    description: "A classic cotton-blend sweatshirt with ribbed cuffs and hem. Soft on the inside, it's perfect for a relaxed, casual look or light warmth.",
    price: 45.00,
    sizes: ["s", "m", "l", "xl", "xxl"],
    colors: ["maroon", "heather-grey", "black"],
    images: {
      maroon: "https://picsum.photos/id/37/400/300",
      "heather-grey": "https://picsum.photos/id/37/400/300",
      black: "https://picsum.photos/id/37/400/300",
    },
  },
  {
    id: 12,
    name: "Nike Pro Hypercool Tights",
    shortDescription: "Maximum ventilation for intense workouts.",
    description: "Designed with strategically placed mesh panels for enhanced airflow. These tights provide a supportive, locked-in feel perfect for high-heat training.",
    price: 59.99,
    sizes: ["s", "m", "l"],
    colors: ["volt", "dark-grey"],
    images: {
      volt: "https://picsum.photos/id/40/400/300",
      "dark-grey": "https://picsum.photos/id/40/400/300",
    },
  },
  {
    id: 13,
    name: "Puma Suede Classic",
    shortDescription: "The timeless, legendary court shoe.",
    description: "An iconic sneaker known for its suede upper and comfortable fit. A cultural favorite that has stood the test of time, great for casual wear.",
    price: 70.00,
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["red", "green", "blue"],
    images: {
      red: "https://picsum.photos/id/42/400/300",
      green: "https://picsum.photos/id/42/400/300",
      blue: "https://picsum.photos/id/42/400/300",
    },
  },
  {
    id: 14,
    name: "Under Armour Hustle Backpack",
    shortDescription: "Durable and water-resistant storage.",
    description: "Features UA Storm technology for a water-resistant finish. Includes a soft-lined laptop sleeve, a large main compartment, and an extra shoe pocket at the bottom.",
    price: 55.00,
    sizes: ["one-size"],
    colors: ["camo", "black", "royal"],
    images: {
      camo: "https://picsum.photos/id/45/400/300",
      black: "https://picsum.photos/id/45/400/300",
      royal: "https://picsum.photos/id/45/400/300",
    },
  },
  {
    id: 15,
    name: "Reebok Training Gloves",
    shortDescription: "Enhanced grip for lifting.",
    description: "Full finger gloves with padded palms and mesh backs for ventilation. Features an adjustable wrist strap for a secure fit, ideal for weight training.",
    price: 25.99,
    sizes: ["m", "l", "xl"],
    colors: ["black", "pink"],
    images: {
      black: "https://picsum.photos/id/48/400/300",
      pink: "https://picsum.photos/id/48/400/300",
    },
  },
  {
    id: 16,
    name: "Adidas Essential Tank Top",
    shortDescription: "Lightweight and breathable for summer.",
    description: "A simple, soft cotton tank top. Perfect for hot weather workouts or as a comfortable layer. Features a classic scoop neck and regular fit.",
    price: 24.99,
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "navy", "orange"],
    images: {
      white: "https://picsum.photos/id/50/400/300",
      navy: "https://picsum.photos/id/50/400/300",
      orange: "https://picsum.photos/id/50/400/300",
    },
  },
  {
    id: 17,
    name: "New Balance Fresh Foam X 1080v12",
    shortDescription: "Cushioned ride for long distances.",
    description: "New Balance's premium running shoe with a Fresh Foam X midsole for supreme softness. Engineered knit upper provides support and breathability.",
    price: 150.00,
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["neon-yellow", "white/black", "mint"],
    images: {
      "neon-yellow": "https://picsum.photos/id/53/400/300",
      "white/black": "https://picsum.photos/id/53/400/300",
      mint: "https://picsum.photos/id/53/400/300",
    },
  },
  {
    id: 18,
    name: "The North Face Beanie",
    shortDescription: "Warm, stretchy, and comfortable knit beanie.",
    description: "Classic cuffed beanie made from a soft acrylic yarn. Provides excellent warmth for cold weather activities or everyday winter wear. One-size-fits-most.",
    price: 28.00,
    sizes: ["one-size"],
    colors: ["grey", "black", "pink"],
    images: {
      grey: "https://picsum.photos/id/56/400/300",
      black: "https://picsum.photos/id/56/400/300",
      pink: "https://picsum.photos/id/56/400/300",
    },
  },
  {
    id: 19,
    name: "Columbia Fleece Full-Zip Jacket",
    shortDescription: "Lightweight layering for everyday warmth.",
    description: "A soft, all-purpose fleece jacket perfect for keeping warm on cool days. Features zippered hand pockets and a full zip front closure.",
    price: 49.99,
    sizes: ["s", "m", "l", "xl", "xxl"],
    colors: ["sky-blue", "grey", "burgundy"],
    images: {
      "sky-blue": "https://picsum.photos/id/59/400/300",
      grey: "https://picsum.photos/id/59/400/300",
      burgundy: "https://picsum.photos/id/59/400/300",
    },
  },
]

export default products